---

- name: "Install the most used packages on servers"
  hosts: all

  vars_files:
    - "vars/main.yml"

  tasks:
    - name: Install APT Packages
      become: yes
      apt:
        pkg: "{{ apt_packages }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Redhat/Fedora Packages
      become: yes
      yum:
        pkg: "{{ rpm_packages }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family']  == 'RedHat'

    - name: show family
      debug: var=ansible_os_family


